### ISSUE TITLE
Should depend on Perl 5.010000 not Perl 5.010001

### ISSUE THREAD

**Issue by ollyg** [LoonyPandora/Dancer-Plugin-Passphrase#10] opened 2014-02-09 11:22 UTC
It's fine to depend on Perl 5.10 but depending on Perl 5.10.1 can cause failed installations. There are Linux distros out there with patched/maintained 5.10 releases only.

If I can work out how D::Z is adding that dependency, I'll write a patch and submit.

**Comment by LoonyPandora** [comment] 2014-02-09 15:00
This should be fixed by v2.0.1 released today: https://metacpan.org/release/JAITKEN/Dancer-Plugin-Passphrase-2.0.1

It was caused by a combination of the `minimum_year` being set to a time when 5.10.1 was released, and using the `switch` feature, which is now marked as experimental. I've removed that, and the minimum version is now correctly set as v5.10

Cheers for the report, and the nudge needed for me to release ;)

**Closed as completed by LoonyPandora** 2014-02-09 15:00 UTC
